// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/logger.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_proto_logger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_proto_logger_proto_rawDescGZIP(), []int{0}
}

func (x *LogRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LogRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *LogRequest) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *LogRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type LogResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProcessedCount int32                  `protobuf:"varint,1,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"`
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_proto_logger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_proto_logger_proto_rawDescGZIP(), []int{1}
}

func (x *LogResponse) GetProcessedCount() int32 {
	if x != nil {
		return x.ProcessedCount
	}
	return 0
}

func (x *LogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_logger_proto protoreflect.FileDescriptor

const file_proto_logger_proto_rawDesc = "" +
	"\n" +
	"\x12proto/logger.proto\x12\x06logger\"u\n" +
	"\n" +
	"LogRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"P\n" +
	"\vLogResponse\x12'\n" +
	"\x0fprocessed_count\x18\x01 \x01(\x05R\x0eprocessedCount\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2H\n" +
	"\rLoggerService\x127\n" +
	"\n" +
	"StreamLogs\x12\x12.logger.LogRequest\x1a\x13.logger.LogResponse(\x01B\x10Z\x0ecrm-core/protob\x06proto3"

var (
	file_proto_logger_proto_rawDescOnce sync.Once
	file_proto_logger_proto_rawDescData []byte
)

func file_proto_logger_proto_rawDescGZIP() []byte {
	file_proto_logger_proto_rawDescOnce.Do(func() {
		file_proto_logger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_logger_proto_rawDesc), len(file_proto_logger_proto_rawDesc)))
	})
	return file_proto_logger_proto_rawDescData
}

var file_proto_logger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_logger_proto_goTypes = []any{
	(*LogRequest)(nil),  // 0: logger.LogRequest
	(*LogResponse)(nil), // 1: logger.LogResponse
}
var file_proto_logger_proto_depIdxs = []int32{
	0, // 0: logger.LoggerService.StreamLogs:input_type -> logger.LogRequest
	1, // 1: logger.LoggerService.StreamLogs:output_type -> logger.LogResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_logger_proto_init() }
func file_proto_logger_proto_init() {
	if File_proto_logger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_logger_proto_rawDesc), len(file_proto_logger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logger_proto_goTypes,
		DependencyIndexes: file_proto_logger_proto_depIdxs,
		MessageInfos:      file_proto_logger_proto_msgTypes,
	}.Build()
	File_proto_logger_proto = out.File
	file_proto_logger_proto_goTypes = nil
	file_proto_logger_proto_depIdxs = nil
}
